[English]
0=
1=Data not found about Total Commander.
2=Plugin Manager terminate.
3=Add plugin
4=(disabled)
5=Respond to extension
6=Enter extension
7=Please select plugin category
8=File
9=is not Total Commander plugin.
10= Use file with extensions:
11=Cancel
12=Lister plugin
13=File path:
14=Detect string:
15=Change
16=Default
17=Load priority
18=Enable plugin
19=Disable plugin
20=View as:
21=Settings
22=File System
23=Lister
24=Packer
25=Packer caps:
26=Can create new archives
27=Can modify existing archives
28=Archive can contain multiple files
29=Can delete files
30=Has options dialog
31=Supports packing in memory
32=Detect archive type by content
33=Allow searching for text in archives
34=Dont open with Enter but with Ctrl+PgDn
35=Configure
36=Interface language
37=Auto apply adjustment
38=One or more lister(s) is opened.
39=To apply changes need restart Total Commander.
40=Continue?
41=Use COMMANDER PATH variable
42=File system plugin
43=Packer plugin
44=Read path to Total Commander INI file from
45=Registry
46=Plugin manager settings
47=About
48=Change
49=Content  plugin
50=Content
51=Info tip on plugins files
52=No
53=Always
54=Only Plugin Manager used
55=Total Commander plugin file
56=Plugin type
57=Unknown
58=Company Name
59=Product Name
60=Product Version
61=Legal Copyright
62=Legal Trademark
63=File Description
64=Comments
65=File information
66=File version
67=Status
68=installed
69=not installed
70=enabled
71=disabled
72=support
